### ISSUE TITLE
Not able to type in a text box

### ISSUE THREAD

**Issue by sunnysachdeva99** [dmtrKovalenko/cypress-real-events#1]
AUT :- https://www.webdriveruniversity.com/Contact-Us/contactus.html
Cypress version : 6.0.0

```
describe('testing real event plugin', () =>{

    it('should ne able to test', () =>{

        cy.visit('https://www.webdriveruniversity.com/Contact-Us/contactus.html')
        cy.get('[name="first_name"]').realType('Automation')

    })
})
```
I found 2 issues:-
1. I am not able to realtype 
2. As shown in the screenshot, code is realType, however, in runner, we see it as realPress

<img width="1434" alt="Screenshot 2020-11-27 at 12 31 52" src="https://user-images.githubusercontent.com/60193936/100420702-dcb09400-30ac-11eb-99dc-3759fd967f59.png">

**Comment by dmtrKovalenko** [comment]
For now type only works with manual click and focus. 

```js
cy.get("input").focus();
cy.realType("some text {enter}"); // type into focused field
```

Yeah that a bugs with a logging. Will fix this, thx.

**Comment by sunnysachdeva99** [comment]
with click() / focus(), it works well. Thanks for the clarification

**Comment by dmtrKovalenko** [comment]
Log message fixed in the latest release
