### ISSUE TITLE
cy.get(...).realHover is not a function ??

### ISSUE THREAD

**Issue by NorfeldtAbtion** [dmtrKovalenko/cypress-real-events#125]
I'm trying to fiddle around with this nice plugin - but can't seem to get it working.

<img width="745" alt="Screenshot 2021-07-15 at 15 50 12" src="https://user-images.githubusercontent.com/53769763/125799230-15bfa7d2-48f9-45ac-8785-4371952bdb47.png">

I just cloned the cypress-example-recipes repo and tried to install it - https://github.com/NorfeldtAbtion/cypress-example-recipes/commit/101df86b8454d78825d47d79feaf2c9e86f604f0

(but it seems that Gleb Bahmutov already installed it 2 months ago)

Am I missing something 🤷‍♂️

**Comment by vitaliy4us** [comment]
I have exactly the same issue: cy.get(...).eq(...).realHover is not a function. My code is:
`cy.get('.header-module--subMenu--1TF98.header-module--menuLevel2--2QGyh').eq(0).realHover();`

**Comment by jam-awake** [comment]
Did you update your `cypress.json` file to refer to the correct support directory, so that Cypress loads that file's content before running your test?

**Comment by snefa** [comment]
I also encountered this issue when I tried using the plugin, I added the following code
`cy.get(OverviewGraph.overviewGraphPeriodSelector).realHover();` 
in a spec file and ran it and got this error
![image](https://user-images.githubusercontent.com/73105185/132689475-c41271e2-7131-4af4-85ba-3be260b063a5.png)

@jam-awake could you please elaborate on what you mean by the correct support directory? I couldn't find any mention of this in the documentation for the plugin...

**Comment by jam-awake** [comment]
AFAIK, plugins only work if they are added in [the Support File](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file). If you don't specify the location when you call `npm cypress:open` (or whatever script you use to start cypress), it will by default look at `./cypress/support/index.js` and load what's there as the support file. If you have changed your project's structure from the default (e.g. `./app/cypress/support/index.js`, then Cypress won't find that file unless you update the support directory to `./app/cypress/support` via your `cypress.json` configuration file or a CLI arg. If you have that file but didn't add the `import "cypress-real-events/support";` code from this plugin in that file, then Cypress will not have those functions on the `cy` object.

**Comment by snefa** [comment]
Ah, thanks for the answer @jam-awake, it seems my path was too specific, had support/commands.ts changed it to "support" - and now the plugin seems to work. 👍

**Comment by bob-lee** [comment]
My `cypress.json` had:
>"supportFile": false,

Now:
>"supportFile": "cypress/support/index.js",

All seems working ok, wonder why this issue is still opened?
