### ISSUE TITLE
Support for Cypress v8?

### ISSUE THREAD

**Issue by alexbjorlig** [dmtrKovalenko/cypress-real-events#130]

**Comment by dmtrKovalenko** [comment]
Did you face any problems with Cypress v8?

**Comment by alexbjorlig** [comment]
Nope - I just used `npm i force` 😅

**Comment by alapanme** [comment]
@dmtrKovalenko Hello can you update the dependencies as per cypress 8.0, getting a lot of dependency conflicts?
