### ISSUE TITLE
Would it be possible to support realhover({x:100,y:200})?

### ISSUE THREAD

**Issue by sandeepvortexa** [dmtrKovalenko/cypress-real-events#161]
In a situation I would like to pass co-ordinates on the screen to appear panel 

e.g.
cy.get('body').realHover({ x: 100,   y: 200  });

is there any workaround for this?

**Comment by dmtrKovalenko** [comment]
You can pass `{x,y}` object in `position`

**Comment by sandeepvortexa** [comment]
Thank you @dmtrKovalenko for your reply.

I have tried 
`cy.get('body').realHover({ position: { x: 939, y: 622 } });`

But did not initiate hover event.
