### ISSUE TITLE
After I call the realHover() method over a menu and perform other actions, the menu is still opened

### ISSUE THREAD

**Issue by jgonzalezalbisu** [dmtrKovalenko/cypress-real-events#162]
Hi @dmtrKovalenko I apologize for not posting it on the first place. I cannot show the actual behavior here as I cannot post anything related to my company code, but basically I have this code block 

````
cy.get(this.menuNavBarMainReportsCSS).realHover(); // After this line is executed, the menu is still opened, like the hover didn't go away.

cy.get(this.menuNavBarItemClassicReportsCSS).realHover(); // I did this to hover over another element within that menu that expands when I hover in the first one, and it solves the problem.

cy.get(this.menuNavBarItemClassicReportsCSS).click();


Would this suffice? Thanks again for your time and apologies again

**Comment by dmtrKovalenko** [comment]
Please provide reproduction or issue will be closed.

**Comment by jgonzalezalbisu** [comment]
Added the description above. Apologies

**Comment by dmtrKovalenko** [comment]
Please provide reproduction (GitHub repo with tests which reproduce your problem)

**Comment by jgonzalezalbisu** [comment]
Hi @dmtrKovalenko , I can't due to the fact that is company code and I cannot post it here. Basically the problem is that the menus I'm hovering over are still opened after I execute the realHover() method. The only way I could find to close them is to hover over another element, but this causes a lot of requests being fired in the test run and it makes the cypress dashboard page to crush.

Can we have a solution for this? Again thanks for your time

**Comment by dmtrKovalenko** [comment]
Sorry, but you can make similar example that reproduce your problem. I understand that you don't want to spend your time on this. But without reproduction I can not help you because I don't want to spend my time trying to understand your problem based on your words. 

Thanks.

**Comment by jgonzalezalbisu** [comment]
Hi @dmtrKovalenko , here you have a public repo of mine with a simple test where you can see this behavior.
https://github.com/jgonzalezalbisu/cypressrealhoverissue

Thanks!

**Comment by heidi-derek** [comment]
It would be useful to have a command such as `.undoHover()` to address this problem. Thanks!

**Comment by mijogu** [comment]
Agreed. I have been unsuccessful in removing the hover/focus of an element that I have used `.realHover()` on. 

In my situation I am able to confirm the presence of text in a div that displays when another element if hovered over. But when I try doing that a second time (on a different element), the original div is still being displayed.

**Comment by PDS42** [comment]
Encountering the same problem here.
An element once hovered with `.realHover()` will stay hovered until tests are done.
`.undoHover()` would be lovely

**Comment by dmtrKovalenko** [comment]
Yep; I will work on this next week

**Comment by jsbaguette** [comment]
Can you explain how you resolved it? the code below if its the resolution doesn't solve the problem here for button

```
cy.get("body").realHover({ position: "topLeft" });
```

**Comment by dmtrKovalenko** [comment]
@jsbaguette I added a note in FAQ how this should be fixed

**Comment by jsbaguette** [comment]
Ye i saw and thank you ! I am going to open a new issue as we have another error
