### ISSUE TITLE
Compatibility with Cypress 9

### ISSUE THREAD

**Issue by ddeboer** [dmtrKovalenko/cypress-real-events#189]
Would it be possible to relax the version constraint in `package.json` to include Cypress 9 or does some work need to be done first to make this library compatible?

**Comment by dmtrKovalenko** [comment]
I think there is no breaking changes that can break us, so need to just reelase as new version

**Comment by ddeboer** [comment]
Oh, just saw there’s already https://github.com/dmtrKovalenko/cypress-real-events/pull/187, but that’s failing on CI.

**Comment by dmtrKovalenko** [comment]
It's just flaky tests 🙈

**Comment by pavlo-poimanov** [comment]
No, it's not flaky tests
It's a problem of types in Cypress.add 
They changed definition
`add(name: string, options: CommandOptions, fn: (...args: any[]) => CanReturnChainable): void`
=> 
`add<T extends keyof Chainable>(name: T, options: CommandOptions, fn: Chainable[T]): void`
Promises now not support as return type, it should be rewritten on Chainable interface or find some type hack to get this it builded

**Comment by dmtrKovalenko** [comment]
Ok, so it will take some time to release it. If you want -- please submit a PR. I am sick now and can not fix it. 

Will do asap

**Comment by SamuelAlev** [comment]
Fixed with https://github.com/dmtrKovalenko/cypress-real-events/pull/199
