### ISSUE TITLE
Error in firefox component testing

### ISSUE THREAD

**Issue by archfz** [dmtrKovalenko/cypress-real-events#194]
I have a simple component test and I am trying to do
```js
cy.get('[name="number"]').realType('asd');
```

But I am getting the following error:
![image](https://user-images.githubusercontent.com/13706730/144109878-df8e106b-5245-4898-9ce5-3cfa250ba733.png)
The only error in console is:
```
Uncaught TypeError: Cypress is undefined
```
This is working properly in Chrome.

Cypress version: 9.0.0
cypress-real-events version: 1.5.1

**Comment by dmtrKovalenko** [comment]
![image](https://user-images.githubusercontent.com/16926049/144110346-4562cbc9-6007-40dc-9933-44b7ba410592.png)

**Comment by archfz** [comment]
Never mind now I see in readme that it's not supported :(. It would have been just great for testing, as for example in firefox you can input anything in a `number` field, but cypress by itself doesn't support this. Let me link the issue https://github.com/cypress-io/cypress/issues/6150
