### ISSUE TITLE
Import error during using cypress 4.9.0 with cypress-real-events

### ISSUE THREAD

**Issue by maximkoshelenko** [dmtrKovalenko/cypress-real-events#20]
Could you please fix import issues for old versions of Cypress.
Demo project attached
[Archive.zip](https://github.com/dmtrKovalenko/cypress-real-events/files/5795770/Archive.zip)
Steps to reproduce:
1. Run 'npm i' into demo project terminal
2. Run 'npx cypress open'
3. Try to run one of tests

**Comment by bliq00** [comment]
I wonder if I'm having the same issue- using cypress-6.4.0 and cypress-real-events-1.1.0.

when running a test, I get an error:

/Users/dictionaryadmin/Desktop/CypressTest/node_modules/cypress-real-events/support.js:1
import { realClick } from "./commands/realClick";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

please let me know if there's any other info I could provide.  thanks

**Comment by dmtrKovalenko** [comment]
@bliq00 do you use any kind of preprocessors?

**Comment by bliq00** [comment]
do you mean like a minify or babelify?  No i don't use anything like that.

**Comment by bliq00** [comment]
Hi, any further thoughts on what might be causing the issue here?

**Comment by dmtrKovalenko** [comment]
No idea, for me it works perfectly. If you can create reproduction will be helpful

**Comment by bliq00** [comment]
what platform are you using?  I'm on MacOS catalina.  I wonder if that makes any difference.

**Comment by dmtrKovalenko** [comment]
I don't care. Make a reproduction with latest cypress -> I will try to fix it

**Comment by Kniaziev** [comment]
Hello, @dmtrKovalenko , I'm getting same issue with 6.4.0 Cypress and cypress-real-events 1.2.0
"SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'"
I've made all according to installation steps from here https://github.com/dmtrKovalenko/cypress-real-events.

<img width="1297" alt="Screenshot 2021-02-08 at 19 00 34" src="https://user-images.githubusercontent.com/9960104/107254425-fa509100-6a3f-11eb-8e87-09a666834530.png">

**Comment by dmtrKovalenko** [comment]
@Kniaziev I understand. But can you provide me a reproduction? Github repository that reproducing the error

**Comment by Kniaziev** [comment]
@dmtrKovalenko I've sent you a link to your email with a zipped folder.

**Comment by Kniaziev** [comment]
@dmtrKovalenko as an additional information error is not present if import `"cypress-real-events/support";` is not in cypress/support/index.js file, anyway using cypress-real-events is not possible.

**Comment by davemello** [comment]
Same issue for me
tsconfig
  "compilerOptions": {

    "target": "ES6",                         
    "module": "commonjs",                    
     "lib": [
        "DOM",
        "ES6"
    ], 

using
const browserify = require('@cypress/browserify-preprocessor');
options.browserifyOptions.plugin.unshift(['tsify']);
as per cypress setup recommendations

**Comment by krzysztofkobrenczuk** [comment]
Hello,
I'm using Cypress 6.5 and faced with the same problem: 
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

I have  on("file:preprocessor", cucumber()); and on("before:browser:launch", in plugins.

**Comment by rupinr** [comment]
@dmtrKovalenko 
https://github.com/rupinr/cypress-cucumber-typescript-example/tree/cypress-real-events This branch has the issue, 
Please take a look at this.

**Comment by Izhaki** [comment]
Under `node_modules/cypress-real-events/support.js`:

```
import { realClick } from "./commands/realClick";
import { realHover } from "./commands/realHover";
import { realSwipe } from "./commands/realSwipe";
import { realPress } from "./commands/realPress";
import { realType } from "./commands/realType";
import { realTouch } from './commands/realTouch';
Cypress.Commands.add("realClick", { prevSubject: true }, realClick);
Cypress.Commands.add("realHover", { prevSubject: true }, realHover);
Cypress.Commands.add("realTouch", { prevSubject: true }, realTouch);
Cypress.Commands.add("realSwipe", { prevSubject: true }, realSwipe);
Cypress.Commands.add("realPress", realPress);
Cypress.Commands.add("realType", realType);
```

This is not a CommonJS file. Anyone importing this library will need some means to transpile them.

I think if cypress is set to work with typescript, this will take care of it. But not for non-typescript projects.

Anyhow, the distribution of this plugin should really not include `import`.
