### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jasonparallel** [dmtrKovalenko/cypress-real-events#208]
Something seems off with typescript support in VS Code. 
Following the recommended config  results in "Property 'realHover' does not exist on type 'Chainable<JQuery<HTMLButtonElement>>'." in VS Code but runs in cypress.

Vs Code appears to be looking at support.d.ts which only contains "export {};"

Changing the index.ts command from "import 'cypress-real-events/support';" to "import 'cypress-real-events/index';" resolves the error in VS Code but errors out when cypress runs.

**Comment by dmtrKovalenko** [comment]
```
{
  "compilerOptions": {
    "types": ["cypress", "cypress-real-events"]
  }
}
```

**Comment by LeBenLeBen** [comment]
I got a similar issue, even with the plugin in the `tsconfig.json` and I was able to fix it by changing the way the plugin is imported.

Instead of using `import 'cypress-real-events/support';` like stated in the docs, I had to use `import 'cypress-real-events';`.

**Comment by dmtrKovalenko** [comment]
Feel free to update the docs
