### ISSUE TITLE
Expand the set of allowed characters for realType()

### ISSUE THREAD

**Issue by sweidmannNF** [dmtrKovalenko/cypress-real-events#213]
I would like to be able to type special language specific characters with realType. For example the german characters "ö", "ä", "ü".

`cy.get('test').realType('Bär')`

It would be nice if I would be able to extend the keyCodeDefinitions at runtime.

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/cypress-real-events/blob/develop/src/keyCodeDefinitions.ts
