### ISSUE TITLE
Cypress Iframe Handling - Failure to interact with Button

### ISSUE THREAD

**Issue by maltewirz** [dmtrKovalenko/cypress-real-events#226]
I am trying to E2E test an auth flow with Cypress that includes a third party method called [BankID](https://www.bankid.no/privat/los-mitt-bankid-problem/test-din-bankid---autentisering/). BankId is integrated through three nested iframes that I can successfully access. However, when I type into the input field via cy.type('12345678912'), BankId does not register this as trusted events and never unlocks the submit button with the arrow.

When using your package via cy.realType('12345678912'), it actually succeeds in unlocking the submit button. However i can never successfully click the submit button, neither with .click() or even the package method .realClick().

The error is: "Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

I uploaded a sample repository with a minimal testing version [here](https://github.com/maltewirz/cypress-iframes).

Any feedback or hints would be greatly appreciated :)

Here is the relevant code:
```
   
/// <reference types="cypress" />
import { skipOn } from '@cypress/skip-test'

describe('Recipe: blogs__iframes', () => {
  skipOn('firefox', () => {
    it('do it more generically', () => {
      const getIframeBody = (identifier) => {
        return cy
        .get(identifier)
        .its('0.contentDocument.body')
        .should('not.be.empty')
        .then(cy.wrap)
      }

      // Visiting the page index.html and getting iframe A
      cy.visit('index.html').contains('XHR in iframe')
      getIframeBody('iframe[data-cy="bankid"]').as('iframeA')

      cy.get('@iframeA').within(() => {
        getIframeBody('iframe[src="https://tools.bankid.no/bankid-test/auth"]').as('iframeB')

        cy.get('@iframeB').within(() => {
          getIframeBody('iframe[src^="https://csfe.bankid.no/CentralServerFEJS"]').as('iframeC')

          // Now we are in the right place and it finds the correct input element.
          // However, normal cypress command .type() fails and we have to use library cypress-real-events,
          // which provides an event firing system that works literally like in puppeteer
          cy.get('@iframeC').find('input[type="tel"]').should('be.visible').realType('12345678912')

          // But for the button below, this library now doesn't help anymore:
          // "Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."
          cy.get('@iframeC').find('button[type="submit"]').should('be.visible').first().realClick()
        })
      })
    })
  })
})
```

**Comment by maltewirz** [comment]
@dmtrKovalenko : Can i somehow support to make investigating this bug easier?

**Comment by dmtrKovalenko** [comment]
```js
  .realClick({ scrollBehavior: false });
```

This is a temporal fix. Looking now how to implement a fix

**Comment by dmtrKovalenko** [comment]
Okay this is not our problem. Your app is actually not working as expected. Iframe is too narrow and button can not be scrolled into view, but we must scroll it into view because without the scroll command won't work. 


<img width="657" alt="image" src="https://user-images.githubusercontent.com/16926049/153626055-32c2a184-a2ee-45a3-9925-01adb8f51830.png">

**Comment by maltewirz** [comment]
Hi, thanks for investigating. I tried your temporal fix and it works for me. I will also research what you pointed out with the "command scroll" to better understand the underlying issue - so far i managed to make the iframe screenwide where the button is visible and the issue was still there.
