### ISSUE TITLE
Tests failing locally in open/headed mode

### ISSUE THREAD

**Issue by drecali** [dmtrKovalenko/cypress-real-events#236]
Many tests in are failing in `click.spec.ts`, `hover.spec.ts`, and `mouse.spec.ts` when I run them locally in the Cypress Test Runner using the `yarn run cypress open` command. Please see the screenshots below.

All tests pass in headless mode.

The reason for the headed failures are that the top offset of the element is expected to be an integer but the actual value has a decimal of usually 0.1875.

Is this issue reproducible? Is it a serious issue?

The fix seems quite easy and works well for me locally. We can just change the Cypress comparison to allow for the small deviation. It seems like a relatively safe change.

<img width="564" alt="image" src="https://user-images.githubusercontent.com/24983797/154049701-1cac293c-52ce-4356-b64e-59c4bca30820.png">

![image](https://user-images.githubusercontent.com/24983797/154046162-28c52563-632b-48f3-a9b4-dc10bf180793.png)

![image](https://user-images.githubusercontent.com/24983797/154046479-136b6bcd-43cd-499d-a090-471e1897c43c.png)

![image](https://user-images.githubusercontent.com/24983797/154046673-3a53c616-87c2-4ea4-a851-602cd372c1ff.png)

![image](https://user-images.githubusercontent.com/24983797/154046338-f7ffac76-1285-47e2-b5b8-16c188341aae.png)

**Comment by dmtrKovalenko** [comment]
Yes, I do think there is not a problem, especially for this plugin which is trying to take the value through the cypress UI that renders the app in iframe. I actually don't know how to make it more stable, so using closeTo is a way to go. 

If you have any idea please provide a PR :)
