### ISSUE TITLE
Missing information in NPM

### ISSUE THREAD

**Issue by baruchiro** [dmtrKovalenko/cypress-real-events#243]
```
❯ npq install cypress-real-events --nosave
  ✔ Checking package maturity
  ✖ Identifying package author...
  ✔ Checking package download popularity
  ✔ Checking availability of a LICENSE
  ✖ Checking availability of a README
  ✔ Identifying package repository...
  ✔ Checking package for pre/post install scripts
  ✔ Checking for known vulnerabilities
Detected possible issues with the following packages:
  [cypress-real-events@latest]
    - the package description has no e-mail associated with author(s). Proceed with care.
    - package has no README file available
```

The README on NPM does not exist.
Also, "the package description has no e-mail associated with author(s)"

**Comment by jwwitherspoon** [comment]
Did some research on this. According to [this issue](https://github.com/serverless/serverless/issues/3157), it looks like this's been happening for a lot of other people and may be an issue with certain npm versions. What version do y'all use?

**Comment by baruchiro** [comment]
@lirantal it takes time but your `npq` is changing to better world 😉

**Comment by lirantal** [comment]
Thanks for bringing this up @baruchiro 👏
