### ISSUE TITLE
Question - Cypress normal click work but realClick not work

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [dmtrKovalenko/cypress-real-events#245]
Hi guys,

I'm going to start apologizing with my terrible English.

I use ReactJS.

I have a div element with onClick event, and when i use cy.click() works fine, but cy.realClick() doesn't work.

Element print:
![Screenshot_1](https://user-images.githubusercontent.com/37240367/159480503-99f79535-d582-4113-8de5-312cd14fdce5.png)

Versions:
"react": "^17.0.2"
"cypress": "9.5.2"
"cypress-real-events": "1.7.0"

**Comment by dmtrKovalenko** [comment]
1. Why do you use realClick at all if cypress default click works? 
2. Please make a reporsitory that reproduces this behavior

**Comment by HidemitsuHashimoto** [comment]
1 - Just for curiosity;
2 - Sorry, is private work so i can't share de code;

**Comment by dmtrKovalenko** [comment]
I can not help you if you can not provide reproduction example, you can make a standalone example that reproduces the same behaviour without your private work. Until you provide it – this issue makes no sense

**Comment by HidemitsuHashimoto** [comment]
Thanks for answers.

I tried simulate an error but i can't, so i'll investigate more.
