### ISSUE TITLE
.realHover() does not work any more after Chrome updates to 100 version

### ISSUE THREAD

**Issue by Alexqatester** [dmtrKovalenko/cypress-real-events#247]
After last Chrome update .realHover() does not work anymore in cypress; 

Version 100.0.4896.60 (Official Build) (64-bit)

**Comment by Andarist** [comment]
I don't see anything new in the `Input.dispatchMouseEvent` docs that would indicate that we need to send some new properties or something: https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchMouseEvent

A further investigation is required here - it would be great if the community could help out here. In the past I had luck in fixing some issues by comparing what this library does and what Playwright does under the hood:
https://github.com/microsoft/playwright/blob/4f1ab2fa6271ae419a95ac1e29130b5c90b78c44/packages/playwright-core/src/server/chromium/crInput.ts#L99

**Comment by alyssa-glean** [comment]
I've also observed `realHover` no longer working, but in our case it's after trying to upgrade to Cypress 10 (but leaving the chrome version fixed at `99.0.4844.84`).

We've bumped the version of this library accordingly and don't have any build errors, but the hover is no longer doing anything.

**Comment by wingleungchoi** [comment]
Did you try to update z-index?
```
      cy.get('<selector>')
        .invoke('attr', 'style', 'z-index: 99999;').realHover();
```

**Comment by h2oearth** [comment]
Any news? Hover is RIP

**Comment by dmtrKovalenko** [comment]
Screenshot from our CI that is successfully running hover spec on Chrome 114 
<img width="893" alt="image" src="https://github.com/dmtrKovalenko/cypress-real-events/assets/16926049/0b9afedd-b1a1-4335-8f80-51650b6d0080">

here is a spec 
https://github.com/dmtrKovalenko/cypress-real-events/blob/develop/cypress/e2e/hover.cy.ts

Closing this until we have any reasonable reproduction
