### ISSUE TITLE
Real Press Arrow keys not working on Mac

### ISSUE THREAD

**Issue by noahgelman** [dmtrKovalenko/cypress-real-events#25]
Confirmed by a coworker. Using the latest version of cypress-real-events and cypress, Using Real Press with the arrow keys down not function properly in a Mac environment.

**Comment by dmtrKovalenko** [comment]
I've been using arrow keys just a day ago :)

`cy.realPress("ArrowDown")` works perfectly. Please provide a reproduction.

**Comment by noahgelman** [comment]
@dmtrKovalenko My coworker is trying to navigate through the options of a select box when it has focus. The select box opens but the selected option is not changed.

**Comment by dmtrKovalenko** [comment]
The issue is not valid without reproduction. Feel free to reopen when you will have a repro.

**Comment by noahgelman** [comment]
@dmtrKovalenko

Here is my repo: https://github.com/noahgelman/cypress-real-event-select-bug

It should navigate between the select options on mac, but it does not.

**Comment by noahgelman** [comment]
@noahgelman Wanted to ping you on this again. A reproduction repo is attached in my previous comment.

**Comment by dmtrKovalenko** [comment]
I am not sure it is possible to fix.
