### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [dmtrKovalenko/cypress-real-events#259]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by JoyceNg331** [comment]
Yes, kindly help, i'm usingCypress 10.0 facing the below installation issue. 

PS C:\Cypress\OneIntel-Cypress> npm install cypress-real-events
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: oneintel-cypress@1.0.0
npm ERR! Found: cypress@10.0.1
npm ERR! node_modules/cypress
npm ERR!   cypress@"^10.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x" from cypress-real-events@1.7.0
npm ERR! node_modules/cypress-real-events
npm ERR!   cypress-real-events@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ngmeiche\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by Abcmsaj** [comment]
Bump!

**Comment by dmtrKovalenko** [comment]
Yes I need some time to do this, unfortunately won’t have free time to work on open source in the nearest future

**Comment by yegorkay** [comment]
@dmtrKovalenko I believe there is a PR that opened up yesterday:

https://github.com/dmtrKovalenko/cypress-real-events/pull/266

**Comment by JoyceNg331** [comment]
So does this means that I can’t use cypress-real-event after I upgraded to Cypress10 ?

Regards,

Joyce Ng

**Comment by dmtrKovalenko** [comment]
Need to test, but very likely — yes

**Comment by mmonteiroc** [comment]
> likely

Means that you actually wont be able to even update. NPM install will crash, as this library will tell you that doesnt support cypress 10

**Comment by joshwooding** [comment]
I think it works without any changes in v10. I've not seen any issues so far.

**Comment by lmiller1990** [comment]
I installed with yarn v1 and it's working fine with Cypress 10. Also, Cypress 10 is using this internally, I don;'t think any code changes are necessary.

The only blocker is newer package managers will complain about the version in `package.json`. You can just do `--force` for now to install it. The package itself functions correctly once installed.

**Comment by joshwooding** [comment]
I'm using it with yarn v3 with Cypress 10 and it works great.

**Comment by dmtrKovalenko** [comment]
Ok then I’ll update the version and publish today. Sorry for the delay.

**Comment by kris-luminar** [comment]
How do you import this plugin into Cypress 10? The instructions in the README are still for Cypress < 10.

> Register new commands by adding this to your cypress/support/index.{js,ts} file.

> import "cypress-real-events/support";

This fails with a message saying 
```
Reference Error: Cypress is not defined
```
my config file looks like
```
/// <reference types='cypress' />

const { defineConfig } = require('cypress');

module.exports = defineConfig({
    e2e: {
        setupNodeEvents(on, config) {
            return require('cypress-real-events/support')(on, config);
        }
    }
});
```

**Comment by lmiller1990** [comment]
That is your `cypress.config.ts`, or **config file**, what you want to do is import it in `cypress/support/index.js` (now called `cypress/support/{e2e,component}.js`.
