### ISSUE TITLE
Triggering events on elements inside iframes calculate position incorrectly

### ISSUE THREAD

**Issue by istateside** [dmtrKovalenko/cypress-real-events#28]
I've been using cypress-real-events in the Cypress tests for our app. Our app renders a page inside of an `<iframe>`.

I've noticed that the events triggered on elements within that iframe are being triggered in the wrong positions, sometimes affecting elements other than the one we're calling the `.realAction()` commands on.

While looking into #26, I tracked down the problem here to [getCypressElementCoordinates](https://github.com/dmtrKovalenko/cypress-real-events/blob/develop/src/getCypressElementCoordinates.ts#L77-L89)

```javascript
  const { x, y, width, height } = htmlElement.getBoundingClientRect();
  const [posX, posY] = getPositionedCoordinates(
    x,
    y,
    width,
    height,
    position ?? "center"
  );


  return {
    x: appFrameX + (window.pageXOffset + posX) * appFrameScale,
    y: appFrameY + (window.pageYOffset + posY) * appFrameScale,
  };
```

This doesn't account for the case where the `htmlElement` is inside of an iframe nested inside of the appFrame. In that situation, `htmlElement.getBoundingClientRect()` returns coordinates relative to its closest iframe.

For us, that nested iframe was positioned 50px from the top of the app Frame, so all of the events triggered with this library were firing 50px higher than we wanted.

**Comment by dmtrKovalenko** [comment]
Yes it makes sense. Probably if the element is located in the nested I frame we need to calculate the position using cdp locator.

**Comment by istateside** [comment]
I have a PR I'm preparing, I'll have it up shortly. I'm just solving it by navigating back up the tree of iframes and using `getBoundingClientRect`. I'm not familiar with the CDP but if there's a cleaner solution using that, that'd be great

**Comment by dmtrKovalenko** [comment]
Please make a PR this will be totally helpful. Make sure that also scale of the iframe should be calculated
