### ISSUE TITLE
Types are not working on Cypress 10 with TypeScript

### ISSUE THREAD

**Issue by nbouvrette** [dmtrKovalenko/cypress-real-events#289]
I use `e2e.ts` with `import 'cypress-real-events/support'` and none of the IntelliSense functionalities work.

I noticed that your `support.d.ts` is also empty.

For example, you can check how [cypress-wait-until](https://www.npmjs.com/package/cypress-wait-until) built their type file as it works very well.

**Comment by dmtrKovalenko** [comment]
Did you upgraded to the latest version? Please double check your installed version of plug-in.

**Comment by nbouvrette** [comment]
Yes all my packages are using thr latest versions

**Comment by nerrante** [comment]
@nbouvrette , I had to add `///<reference types="cypress-real-events" />` to the top of support/index.d.ts in Cypress to get it to work. Hope that helps.

**Comment by nbouvrette** [comment]
Oh yeah this can be a workaround, but when the types are correctly included with the module, they should be available automatically when the package is imported.
