### ISSUE TITLE
realPress() Meta modifier not undoing input text

### ISSUE THREAD

**Issue by tuckergordon** [dmtrKovalenko/cypress-real-events#292]
I'd like to write a Cypress test to verify that pressing cmd-z in an <input> text undoes the previously-typed text. For example, the following works on winodows:

```js
cy.get("input").focus();
cy.realType("abc")
cy.get("input").should('have.value', 'abc')
cy.realPress(["Control", "z"])
cy.get("input").should('have.value', '')
```

However it doesn't seem to be working on Mac when using the <kbd>meta</kbd> key:
```js
it('can undo input text', () => {
  cy.get('input[type=text]').focus();
  cy.realType('abc');
  cy.get('input[type=text]').should('have.value', 'abc');
  cy.realPress(['Meta', 'Z']);
  cy.get('input[type=text]').should('have.value', '');
});
```

I posted a [StackOverflow question](https://stackoverflow.com/questions/73367009/cypress-undo-input-text) about it and it seems like this could be an issue specific to Mac and the Meta key (windows + ctrl key [seems to work fine](https://stackoverflow.com/questions/73367009/cypress-undo-input-text/73367106?noredirect=1#comment129589624_73367106)).

Here is a [repo](https://github.com/tuckergordon/cypress-input-text-undo) demonstrating the issue. Don't see much in the docs or issue tickets about this, so wondering if I'm missing something or if this is a bug?

**Comment by dmtrKovalenko** [comment]
Can you try to use Meta key it is a valid key in our realPress it may work

**Comment by tuckergordon** [comment]
Meta key doesn't work unfortunately - see my sample [repo](https://github.com/tuckergordon/cypress-input-text-undo) for an example. Also updated the issue ticket to include the code snippet from the repo to make it clearer

**Comment by OleksandrRakovets** [comment]
Experiencing similar issue on macOS when trying to select all with `cy.realPress(["Meta", "a"])`

**Comment by dmtrKovalenko** [comment]
I think this is already by #569
