### ISSUE TITLE
Pressing enter with realPress inside should-callback is ran twice

### ISSUE THREAD

**Issue by ArktinenSieni** [dmtrKovalenko/cypress-real-events#304]
Hey!

Trying to figure out if the issue is with Cypress or the real-events.

Following code gives enter-event twice:
```
cy.focused().should(() => {
  cy.realPress('enter');
  expect(someAssertion).to.be(true);
});
```

I am aware that this callback includes side effects, and is intentional in this case.

**Comment by dmtrKovalenko** [comment]
You should not initiate actions within should callback as it may be retried by cypress itself https://github.com/dmtrKovalenko/cypress-real-events#1-why-cyrealhover-hovering-state-does-not-show-in-the-visual-regression-services
