### ISSUE TITLE
How to get actual background color since user cannot get screenshot when .realHover() effect

### ISSUE THREAD

**Issue by 787681277** [dmtrKovalenko/cypress-real-events#305]
I get rgba(0,0,0,0) background-color with below code, which makes assertion difficult.How can I get actual background-color rgb(232 232 232):

code:
        cy.get(activeTab2)
          .realHover()
          .should('have.css', 'background-color','rgb(232, 232, 232)');

**Comment by dmtrKovalenko** [comment]
Looks like you have the issue in your code. https://github.com/dmtrKovalenko/cypress-real-events/blob/29311472782bc5ee477da3909a21a236efbdab63/cypress/e2e/hover.cy.ts#L7-L10 here is an example that works you can run it on your own
