### ISSUE TITLE
Testing with debounced event

### ISSUE THREAD

**Issue by convers39** [dmtrKovalenko/cypress-real-events#311]
I am using realHover to test the mouseover/pointerover event, and implemented debounce as I would like to limit the events when moving the mouse.

When I try to test with realHover, `cy.wait` does not help. Is there any workaround to deal with this issue?

```ts
              cy.wrap($canvas)
                .realHover({
                  position: { x, y },
                })
                .wait(800) // -> not working, my debounce time is set to be 300ms

```

```tsx
import { debounce } from "lodash";

    const debounceOnHover = useRef(debounce(onHover, 300))
        .current;

```

**Comment by dmtrKovalenko** [comment]
You need to use cy.wait() before the realHover as a standalone command. 


```jsx
cy.wait(800);
cy.realHover(...)
```

**Comment by convers39** [comment]
> You need to use cy.wait() before the realHover as a standalone command.
> 
> ```js
> cy.wait(800);
> cy.realHover(...)
> ```

Thank you for your reply, not sure why did not get luck in my case, I tried both

```ts
cy.wrap($el).wait(800).realHover()

cy.wait(800)
cy.wrap($el).realHover()
```

**Comment by dmtrKovalenko** [comment]
Please provide a reporduction if you think this is a bug
