### ISSUE TITLE
Support x/y for mouseDown and mouseUp.

### ISSUE THREAD

**Issue by maxbogue** [dmtrKovalenko/cypress-real-events#316]
I was trying to test some canvas interactions that use a click and drag interaction and I realized there's no way to specify the actual x/y of a mouse down/up command. Could that be added?

**Comment by dmtrKovalenko** [comment]
You can pass { x: number, y: number } for the position option. Make sure that it is not the javascript but CDP coordinates, related to the whole tab

**Comment by maxbogue** [comment]
Why not allow a relative x/y to be passed in as well, like with mouseMove, so your user doesn't have to compute whole-tab coordinates? Or is there some easy way to do that I'm missing?

**Comment by dmtrKovalenko** [comment]
That could be a great feature, but somebody needs to write some code to actually calculate the position! That could be you :)

(the very warm welcome to become contributor)
