### ISSUE TITLE
Calculation of coordinates are wrong when Cypress scales the application view port

### ISSUE THREAD

**Issue by Im-a-Train** [dmtrKovalenko/cypress-real-events#317]
**Problem**
Depending on the Cypress view port scaling, the coordinates are calculated different and with the wrong proportions.

**Code to reproduce:**
```
describe('Real Event Demo', () => {
    beforeEach(() => {
        cy.visit('https://www.pdftron.com/webviewer/demo/')
    });

    it('Insert Rectangle', () => {
        cy.get('iframe[id="webviewer-1"]')
            .its('0.contentDocument.body')
            .then(body => cy.wrap(body))
            .within(() => {
                cy.get('div[data-element="shapeToolGroupButton"]').click()
                const startPos = {x: 100, y: 100}
                const endPos = {x: 200, y: 200}

                cy.get('div[id=pageContainer1]')
                    .realMouseDown({button: 'left', position: startPos})
                    .realMouseMove(endPos.x, endPos.y)
                    .realMouseUp({button: 'left', position: endPos});
            })
    });
});
```
**Current Behavior:**
The same test code produces different output, depending on the view port scaling:
View Port 100%:
![image](https://user-images.githubusercontent.com/42909317/199715741-c70756e4-393f-45fd-bc79-213eed379734.png)
View Port 56%:
![image](https://user-images.githubusercontent.com/42909317/199715979-72950c95-bb7d-403f-ac8c-29f8732b6c8e.png)

https://user-images.githubusercontent.com/42909317/199715997-786c40f2-2cff-49ad-aa6e-546e7f02ecd2.mp4

**Expected Behavior**
The view port scaling should not affect the test output.
**Versions**
- Cypress: 9.7.0
- cypress-real-events: 1.7.2

**Comment by Im-a-Train** [comment]
I could also reproduce the problem with the click test from this repo:
Viewport Scaling to 50%:
![image](https://user-images.githubusercontent.com/42909317/200781979-b17da6d5-ca7e-4e2f-9cb7-01666f9b86f3.png)
Viewport Scaling to 100%:
![image](https://user-images.githubusercontent.com/42909317/200782137-a0ca17e4-c7fd-4b94-8d4f-c5d30a2c64ff.png)

I'm working on a Pull Request to fix this problem.

**Comment by wtachau** [comment]
Thank you for digging into this— we are also having this issue!

**Comment by wtachau** [comment]
Thanks all! New release is working like a charm :)
