### ISSUE TITLE
Cypress 11 version update

### ISSUE THREAD

**Issue by JoanEsquivel** [dmtrKovalenko/cypress-real-events#324]
dev cypress@"11.0.0" from the root project
npm WARN   5 more (@4tw/cypress-drag-drop, @testing-library/cypress, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer cypress@"^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x || ^10.x" from cypress-real-events@1.7.2

**Comment by piwysocki** [comment]
It's already fixed in v1.7.3

**Comment by piwysocki** [comment]
https://github.com/dmtrKovalenko/cypress-real-events/pull/366
