### ISSUE TITLE
cypress-real-events in combination with beforeunload event causes flaky page leave dialog

### ISSUE THREAD

**Issue by maartencardinaels** [dmtrKovalenko/cypress-real-events#330]
We have testscases where we combine 
- cypress-real-events
- application code that is using the beforeunload event to prevent the user from leaving the page when it's in a dirty state, see image below:

![image](https://user-images.githubusercontent.com/64408852/202211320-0cb5fbb1-209a-4fa4-8720-26b0d2ca9a2c.png)

From the moment one of our testcases uses a cypress-real-event and next we have a test that leaves a page in a dirty state (by moving on to the next test), the beforeunload interrupt is being triggered (although not every time...), causing the Cypress run to pause. 

We tried to [disable beforeunload](https://glebbahmutov.com/blog/onbeforeunload/) event but without success. We checked the code of cypress-real-events but were not sure where this conflict is coming from.

**Comment by dmtrKovalenko** [comment]
Please provide a repository with reproduction of the problem, otherwise the issue will not be accepted

**Comment by Im-a-Train** [comment]
Hi @maartencardinaels 
I had the same Issue like you and described the problem in the [FAQ](https://github.com/dmtrKovalenko/cypress-real-events#3-why-do-i-get-are-you-sure-popups-when-i-am-using-real-events-and-why-i-do-not-get-them-while-using-the-normal-cypress-clicks)
This code works for me to disable the beforeunload event.
But you have to call it directly after you made the `cy.visit`
```
// create proxy event listener to drop before unload events, which prevent to reload the page in some cases
cy.window().then(win => {
    const original = win.addEventListener;
    win.addEventListener = (...args: any) => {
        // ignore beforeunload events e.g. Save Warning
        if (args && args[0] === 'beforeunload') {
            cy.log('beforeunload event ignored');
            return null;
        }
        return original.apply(win, args);
    };
});
```
Here is some additional information about this problem:
https://lightrun.com/answers/cypress-io-cypress-electron-browser-hangserrors-on-apps-with-windowonbeforeunload-alerts
https://glebbahmutov.com/blog/onbeforeunload/

Hope this helps
