### ISSUE TITLE
Support for Cypress 12

### ISSUE THREAD

**Issue by jfairchild-aumni** [dmtrKovalenko/cypress-real-events#353]
Would this be easy to support? I understand there are changes to how cypress handles custom commands, so it isn't obvious to me.

**Comment by dmtrKovalenko** [comment]
oh my god they are making breaking changes every month! need to test it

**Comment by seggewiss** [comment]
We at Shopware also had no Problems once upgraded to cypress 12.0.1.

**Comment by mmonteiroc** [comment]
It would be really interesting to add this support. Cypress fixed the famous issue of "detached from dom" so plenty of people ( like us ) would like to upgrade

**Comment by vlcekr** [comment]
Yes this is currently blocking me to upgrade Cypress to 12.0.2

**Comment by piwysocki** [comment]
https://github.com/dmtrKovalenko/cypress-real-events/pull/366

**Comment by mmonteiroc** [comment]
> Yes this is currently blocking me to upgrade Cypress to 12.0.2

As it seems to work, you could just do an npm i —force ;(

**Comment by dmtrKovalenko** [comment]
released in 1.7.6
