### ISSUE TITLE
How to capture tooltip in screenshot when using cy.realHover()/cy.realClick()?

### ISSUE THREAD

**Issue by 787681277** [dmtrKovalenko/cypress-real-events#357]
When using realClick to show the tooltip of a tab when clicking, the tooltip is gone when taking a screenshot.
I tried matchImageSnapshot from cypress-image-snapshot but both didn't work.
When looking the tab(run test case through command "npx cypress open --component"), I can clearly see that the tooltip is displayed when click the button but it gets lost when the screenshot is taken.

The only thing that works is checking the displayed tooltip's text itself by doing the following:
//working
cy.get('div.show > div').should('have.text', 'Trash')

// not working
cy.get(tab_tooltipNext).realClick();
cy.matchImageSnapshot('trigger-click-tooltip-hideTooltipOnBlur-true');

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/cypress-real-events#1-why-cyrealhover-hovering-state-does-not-show-in-the-visual-regression-services
