### ISSUE TITLE
realHover is not a function

### ISSUE THREAD

**Issue by vtlnkhn** [dmtrKovalenko/cypress-real-events#358]
Hi all!

I've installed 'cypress-real-events', 
added `import 'cypress-real-events`(tried 'cypress-real-events/support' too) to cypress/support/index.ts file,
also added to tsconfig.json - `"types": ["cypress"]`
but it still doesn't work 

What am I missing? 
P.S. project on Next.JS + TypeScript 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/89406758/206435544-be2583d7-c76a-44c3-bd6a-b7fe5b6c60c8.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/89406758/206435596-378c4a21-2f08-42a6-b5dd-874e74872948.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/89406758/206435900-5fae5640-d74b-490c-9472-79ac03aa7695.png">

**Comment by vtlnkhn** [comment]
UPD: fixed by adding import into 'commands' instead of 'index', but still getting TS error

**Comment by mitchwd** [comment]
@vtlnkhn I have a `tsconfig.json` in my cypress folder, and I added the following line to the types section, which seems to remove the TS error...

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext", "dom"],
    "types": [
      "cypress",
      "node",
      "cypress-real-events"
    ]
  },
  "include": ["**/*.ts"]
}

```

**Comment by vtlnkhn** [comment]
> @vtlnkhn I have a `tsconfig.json` in my cypress folder, and I added the following line to the types section, which seems to remove the TS error...
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "ESNext",
>     "lib": ["ESNext", "dom"],
>     "types": [
>       "cypress",
>       "node",
>       "cypress-real-events"
>     ]
>   },
>   "include": ["**/*.ts"]
> }
> ```
> 
> @dmtrKovalenko I've created a tiny PR to add this to the README:

@mitchwd it helped, bro, thank you so much)
