### ISSUE TITLE
Real Click not working on GithubAction 

### ISSUE THREAD

**Issue by TammyTorres** [dmtrKovalenko/cypress-real-events#39]
I recently added the dependency to my project which is running on github action , for some reason locally works fine, but on the github action when runs, then I got this error:

**CypressError: `cy.click()` can only be called on a single element. Your subject contained 2 elements. Pass `{ multiple: true }` if you want to serially click each element.**

"react": "^16.13.1",
 "cypress": "^5.3.0",

any ideas??

**Comment by dmtrKovalenko** [comment]
It looks not related to the `cy.realClick` at all, because we are not using `cy.click`. Please provide a reproduction if you are sure that this problem comes from real events
