### ISSUE TITLE
.realClick() is not a function

### ISSUE THREAD

**Issue by namanharness** [dmtrKovalenko/cypress-real-events#390]
Hi team, i am using this package and started to get this error recently , how to resolve this?
<img width="529" alt="image" src="https://user-images.githubusercontent.com/110456765/211731060-6b6ab8de-7d61-4313-b98c-8d591041d5ad.png">

**Comment by JasonFairchild** [comment]
Getting what appears to be the same, but for realMouseWheel. RealClick seems to work/be recognized.

**Comment by Dzanan91** [comment]
Same for realHover. I keep getting "not a function" error

**Comment by konchahina-o** [comment]
Also getting same errors. Will it be fixed?

**Comment by adamdrake210** [comment]
I am getting this error for `realMouseWheel`. I checked the `index.d.ts` file and don't see it and I don't see the function in the `commands` folder:
![image](https://user-images.githubusercontent.com/6083945/222443887-1a31bbe5-8b57-4919-9dc2-2943b358eb66.png)

Its in the README: https://github.com/dmtrKovalenko/cypress-real-events#cyrealmousewheel

So something is not correct here. Has this functionality been removed but the README not updated? Thanks.

**Comment by raul-wizeline** [comment]
I moved the `import "cypress-real-events"` to the e2e.js file and the problem got solved.

**Comment by cjcenizal** [comment]
Thanks @raul-wp ! That solved it for me.
