### ISSUE TITLE
Support on setup of cypress-real-events?

### ISSUE THREAD

**Issue by BJSS-russell-pollock** [dmtrKovalenko/cypress-real-events#406]
Hi - apologies, this isn't an 'issue' but I'm wondering about support for correct setup in Cypress v12.

I have `cypress-real-events` installed and it works as expected in Cypress.

However, the type-script support disappears from the test file `component-tests/e2e/tests/test.cy.ts` if I do not have `component-tests/support/commands.ts` or `component-tests/support/e2e.ts` open in VSCode. The test file is using `.realHover()`

The error shown in VSCode is: 

`Property realHover does not exist on type Chainable<JQuery<HTMLElement>>.ts(2339)`

I've added ` "types": ["node", "cypress", "cypress-real-events"]` to my tsconfig.json and it's fine in the commands.ts using 

```
import 'cypress-real-events'

Cypress.Commands.add('resetRealHover', () => {
  cy.get('body').realHover({ position: 'topLeft' })
})
```

Are there any other steps I should be doing for v12?

**Comment by BJSS-russell-pollock** [comment]
Turned out my tsconfig.json was not setup correctly and the command and e2e files being open somehow made it so everything worked. All fine now.

**Comment by lmiller1990** [comment]
Should we close this one @BJSS-russell-pollock? To check, I tried using Cypress Real Events in the latest Cypress (12.8.1). Working as expected.

**Comment by BJSS-russell-pollock** [comment]
yes please @lmiller1990 - it was just my noob status of setting up tsconfig.

**Comment by lmiller1990** [comment]
Can you close it? I do not have access to this repo to close your issue. Thanks!

**Comment by DavidLGoldberg** [comment]
I had a similar issue and had to add these to the top of my cypress test file:
/// <reference types="cypress" />
/// <reference types="cypress-real-events" />
