### ISSUE TITLE
Failed request to chrome devtools protocol

### ISSUE THREAD

**Issue by Amitkahlon** [dmtrKovalenko/cypress-real-events#407]
I'm getting an error lately, running the tests locally and on the ci.

> Failed request to chrome devtools protocol. This can happen if cypress lost connection to the browser or the command itself is not valid. Original cypress error: Error: Invalid parameters (Failed to deserialize params.x - BINDINGS: double value expected at position 27) 
_node_modules/cypress-real-events/fireCdpCommand.js:19:1_

**Comment by admalik100** [comment]
@Amitkahlon using a browser other than chrome? 
This error appears for me when using webkit.

**Comment by Amitkahlon** [comment]
@admalik100 I actually found out I was doing something wrong! sorry for bothering...
