### ISSUE TITLE
Library does not work on windows chrome

### ISSUE THREAD

**Issue by hubertsuprunowicz** [dmtrKovalenko/cypress-real-events#41]
The library does not work on Windows chrome BUT seems to work on Windows headless and Linux.
Tested it with realHover and realClick.

Tried with:
- Chrome 89
- Node 12.18.3
- cypress 6.5.0 & 6.8.0
- typescript
- cypress-real-events 1.2.0 & 1.3.0
- yarn
- vite

**Comment by dmtrKovalenko** [comment]
I think I won't work on this because I don't like windows issues :D 
This should not be a problem at all because pupeteer works on windows and I think cypress has everything setup right for windows automation. So if you want this to be fixed – feel free to open PR
