### ISSUE TITLE
realMouseWheel is not a function

### ISSUE THREAD

**Issue by scorpyto** [dmtrKovalenko/cypress-real-events#425]
For the first time when I try to use this command it leads to error `cy.get(...).realMouseWheel is not a function`. Tried with "cy.xpath" and "cy.get" both didn't work. Real events are already imported - I am using "realSwipe" and "realClick" in my code above in the same class.

**Comment by martrohelsanchez** [comment]
@scorpyto I'm also experiencing this. Have you found a solution to this?

**Comment by scottchildsalkami** [comment]
Is this due to it not having been merged to the main branch yet?

**Comment by scottchildsalkami** [comment]
This doesn't quite do what I'm looking for as it is a programmatic scroll, whereas I need to emulate a mouse scroll to verify that the contents under a modal do not scroll

**Comment by dmtrKovalenko** [comment]
That was my bad – the release automation broke silently. I am sorry for such a long delay. Released in 1.8.1

**Comment by scorpyto** [comment]
cy.get('#grid').realMouseWheel({ deltaX: 500 }) again leads to error "cy.get(...).realMouseWheel is not a function"
I remember few days ago it was working.

**Comment by scorpyto** [comment]
@dmtrKovalenko I have the same issue which was fixed few months ago "cy.xpath(...).realMouseWheel is not a function". Could you please check? 
Thanks in advance!
