### ISSUE TITLE
Support of mutated vowels

### ISSUE THREAD

**Issue by BambiMC** [dmtrKovalenko/cypress-real-events#432]
Currently there is no support for mutated vowels.
Steps to reproduce: Try to run:
cy.realType("über");
Error: Unrecognized character "ü".

The normal function cy.type() does allow the use of mutated vowels.
Is this something you could support?
Might be a bug as you state "text to type. Should be around the same as cypress's type command argument".

Thanks in advance!

**Comment by dmtrKovalenko** [comment]
I think it’s not, because even in the real playwright it is not executed as real typing but more like text pasting from keyboard. 

So in this case just use normal cy.type
