### ISSUE TITLE
realPress() is not working when navigation keys passed as arguments [for example cy.realPress('PageDown')]

### ISSUE THREAD

**Issue by mokuq** [dmtrKovalenko/cypress-real-events#467]
Dear Team.
When I try to pass any navigation keys realPress is not changing of content on the page. 
I tried:     
cy.realPress('{pagedown}');
cy.realPress('PageDown');
Another keyboard navigation key code also are not changing position on the page:
1) cy.realPress('ArrowDown'); 
2) cy.realPress('End');
3) cy.realPress('Home');
4) cy.realPress('ArrowUp');
At least 2 others are working: cy.realPress('Tab') and cy.realPress('Enter').

Configuration:
"cypress-real-events": "^1.7.6"
"cypress": "^10.11.0"
Chrome: 112.0.5615.138
npm version: 6.14.18

If you need additional information, please, let me know.

**Comment by cami-dev** [comment]
I'm having the same issue, need to be able to test Home and End. No update on support for this?
