### ISSUE TITLE
Flakey tests with realHover

### ISSUE THREAD

**Issue by LewisCraik** [dmtrKovalenko/cypress-real-events#478]
I am running a suite of tests on a navigation menu, where hovering over a main menu item shows a submenu. There are 42 test cases in total.

However, each time I run through the suite of tests there are 4 to 8 tests failing, as realHover did not trigger the submenu to be displayed. It is different tests (submenu items) failing each time, so not an issue with the menu, and it any case the same menu items are passing for other tests.

I have updated to the latest 1.8.1 release (and Cypress 12.12.0) and tried setting different positions in the options, but it is still not reliably triggering 100%.

Looking through the Cypress events the get I use is working correctly, as when viewing the history the menu item to hover over is highlighted.

Is this something I am missing? Or could it be related to the lack of actionability waits (#270)?

**Comment by dmtrKovalenko** [comment]
Please provide a reproduction of such a flaky tests and I can take a look
