### ISSUE TITLE
realHover works for chrome and edge. Fails for safari and firefox

### ISSUE THREAD

**Issue by mkathu** [dmtrKovalenko/cypress-real-events#479]
`Failed request to chrome devtools protocol. This can happen if cypress lost connection to the browser or the command itself is not valid. Original cypress error: Error: No handler registered for: 'remote:debugger:protocol'`

Error is displayed when tests are executed for safari and firefox.

<img width="1629" alt="Screenshot 2023-05-18 at 2 44 10 PM 1" src="https://github.com/dmtrKovalenko/cypress-real-events/assets/7846128/953cd79d-7d30-475a-9911-399d2a5c83db">

**Comment by dmtrKovalenko** [comment]
That is expected and mentioned in readme
