### ISSUE TITLE
Shift+Tab syntax

### ISSUE THREAD

**Issue by noahgelman** [dmtrKovalenko/cypress-real-events#5]
Hi, loving the plugin so far.

I have a question about the syntax for Shift+Tab. I can't seem to get the syntax right without throwing an error. Can you add an example of multi-key pressing to the README?

**Comment by dmtrKovalenko** [comment]
That is a nice question. I am afraid that it is not possible for now. 
Will add a new feature in the next release

**Comment by noahgelman** [comment]
@dmtrKovalenko Thank you for the response.
Is a estimated release schedule you have in mind?

**Comment by dmtrKovalenko** [comment]
Next weekends. May be earlier :)
If you would like to open PR - welcome 🤓

**Comment by noahgelman** [comment]
@dmtrKovalenko I'm still figuring it out and exploring, but I might just do that :)

**Comment by kolaps33** [comment]
Hi @dmtrKovalenko 
I am experimenting and trying to implement your package :) So far it looks great :) (tried some arrow keys and Tab key)

As well I would like need Shift+TAB behavior. 

I was tried in very simple JS Fiddle example, how real browser does it:
https://jsfiddle.net/kolaps33/d1jhpf5y/6/

![image](https://user-images.githubusercontent.com/22620150/102613208-6397e000-4132-11eb-9283-5adb1fa06e1f.png)

What I can observe I get two events first just with keycode like Shift key and then second with Tab key + "shiftKey" prop set to true. 

So maybe  when you fire event if you could set to the option {shiftKey: true} ? ( (just guessing)
and if I would call it with your package something like: 
`realPress("Tab", {shiftKey: true})`

Thank you for any update. :)

**Comment by dmtrKovalenko** [comment]
## Requirements 

`cy.realPress` command should have an ability to run the keyboard shortcuts. Proposed syntax:

```js
cy.realPress("Shift+Tab")
cy.realPress("Ctrl+Alt+Down")

cy.get("input").realClick()
cy.realPress("Command+Alt+H")
```

All of these even should create the right modifiers (shift/ctrl/cmd) and run the keydown/keyup events. 
This also must be typed using new [typescript template literal syntax](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html)

**Comment by kolaps33** [comment]
Thank you for clarification 👍 , I am not really experienced with Cypress. Just consuming it during keyboard navigation tests. Therefore, I will rather prefer to wait for you or anyone who will bring Shift+TAB functionality to this package :). Thank you very much for your initiative.

**Comment by wachunga** [comment]
@dmtrKovalenko one place this would be useful is copy/paste via Command+A, which isn't possible with simulated events currently.

**Comment by nnaydenow** [comment]
Hi @dmtrKovalenko,

Does this support combinations like: `cy.realPress(["Control", "A"]` with the idea to simulate select all and etc?

**Comment by dmtrKovalenko** [comment]
I don't know 😬 if it doesn't work than probably it's not.
