### ISSUE TITLE
Move prettier to dev dependencies

### ISSUE THREAD

**Issue by lucy-m** [dmtrKovalenko/cypress-real-events#528]
Hello,

Prettier was added to the project two weeks ago to enforce code formatting, but it has been added to the dependencies section of package.json. Prettier should be a dev dependency.

This may be breaking for users of this library who are using version 2.x of Prettier, as installing this library causes version 3.0 of prettier to be installed and used.

Can prettier please be moved to the dev dependencies section?

**Comment by dmtrKovalenko** [comment]
Oops that is an issue

**Comment by lucy-m** [comment]
Thanks for resolving this quickly

**Comment by dmtrKovalenko** [comment]
releasedd in 1.10

**Comment by joshwooding** [comment]
Looks like prettier is still a dependency. I've raised #532 to remove it
