### ISSUE TITLE
Make `getCypressElementCoordinates` available to use in cy tests.

### ISSUE THREAD

**Issue by dulgeoion** [dmtrKovalenko/cypress-real-events#537]
Hey! 
I want to calculate the exact coordinates for an accurate `onMouseMove` event. The only problem is that the `getCypressElementCoordinates` utility function is not accessible.

My case: I need to test the reordering of rows in a table by drag and drop. So I want to get the coordinates of the last row and provide it as a destination point for the mouse move event fired on the first row. 

Thank you for your attention and hope we can resolve this 🙏

**Comment by dmtrKovalenko** [comment]
I don't think this will be possible from the perspective of
how cypress loads plugins. It's not idiomatic cypress. 

You should instead locate the latest row and call mouseMove on the latest row target like. 

```
cy.get(latest).mouseMove(...)
```

**Comment by dulgeoion** [comment]
That is a good idea @dmtrKovalenko! I very much appreciate your feedback. 🙇
