### ISSUE TITLE
Not compatible with cypress 13

### ISSUE THREAD

**Issue by pat-convex** [dmtrKovalenko/cypress-real-events#550]
This morning I upgraded to the latest cypress 13 so i can try the new cypress replay feature but i got npm error that it is not compatible and i need to downgrade to version 12. 

Thanks

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: workflow@1.0.0
npm ERR! Found: cypress@13.0.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x || ^10.x || ^11.x || ^12.x" from cypress-real-events@1.10.1
npm ERR! node_modules/cypress-real-events
npm ERR!   cypress-real-events@"^1.10.0" from the root project
npm ERR!

**Comment by matmannion** [comment]
Adding this to the package.json should allow you to use this until a compatible version is released.

```json
"overrides": {
  "cypress-real-events": {
    "cypress": "$cypress"
  }
}
```

**Comment by dmtrKovalenko** [comment]
There are some issues with running our CI on the version 13

**Comment by tsaber** [comment]
npm ERR! While resolving: webauftritt-cy@1.0.0
npm ERR! Found: cypress@13.1.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"13.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^4.x || ^5.x || ^6.x || ^7.x || ^8.x || ^9.x || ^10.x || ^11.x || ^12.x" from cypress-real-events@1.10.2
npm ERR! node_modules/cypress-real-events
npm ERR!   dev cypress-real-events@"^1.10.2" from the root project

still getting this error when updating

**Comment by dmtrKovalenko** [comment]
Published https://unpkg.com/cypress-real-events@1.10.3/package.json with a correct change
