### ISSUE TITLE
Having problems getting it to work.

### ISSUE THREAD

**Issue by alexander-paterson** [dmtrKovalenko/cypress-real-events#558]
I'm using the latest version of Cypress ([v13.2.0](https://on.cypress.io/changelog#13-2-0)) and have installed the real events plugin using `npm install cypress-real-events` 

The readme states to 

> Register new commands by adding this to your cypress/support/index.{js,ts} file.

There isn't an index file, there is an `e2e.js` file which I have added `import 'cypress-real-events';` to.

In my test I have replaced a `.type('blah')` with a `.realType('blah')` but nothing seems to get entered into the textbox.

Not quite sure what I'm doing wrong?

**Comment by dmtrKovalenko** [comment]
Please provide standalone reproduction. Otherwise this issue will be incomplete and closed.

**Comment by alexander-paterson** [comment]
I don't know what to say, I literally have one file I'm playing around with and the real-events plugin installed on a brand-new installation of Cypress.


![1hddflfjeA](https://github.com/dmtrKovalenko/cypress-real-events/assets/931083/c5a329df-33d3-4f94-b522-5cc3a4859266)
![6iXOV403W7](https://github.com/dmtrKovalenko/cypress-real-events/assets/931083/c065a582-8857-4de9-b2cd-1034f5cd4637)
![81JIx7vz3e](https://github.com/dmtrKovalenko/cypress-real-events/assets/931083/27057bbd-9c49-4610-8750-a21a9ed8e54d)

![2023-09-18_21-44-44](https://github.com/dmtrKovalenko/cypress-real-events/assets/931083/6a01d475-3b4d-4f79-87d4-20cb3181fb57)

**Comment by dmtrKovalenko** [comment]
Without a reproduction I won’t be able to help. Create a repository.
