### ISSUE TITLE
Support alt/control modifiers for events

### ISSUE THREAD

**Issue by SvetlanaNapris** [dmtrKovalenko/cypress-real-events#561]
In my project I'm using mouseDown() event with Shift modifier ant it works perfectly for me:`element.realMouseDown({ x: posX, y: posY, button: mouseButton, shiftKey: shift })`. But I figured it out that it's the only modifier supported so far. And I need to use Alt and Ctrl modifiers in my tests as well. Is there any reason it's not implemented yet? If it's only lack of time issue, is it ok if I'll create PR with updated code to support all modifiers from keyToModifierBitMap?

**Comment by dmtrKovalenko** [comment]
Feel free to open a PR

**Comment by dmtrKovalenko** [comment]
Closed by #568
