### ISSUE TITLE
Can display the swipe path when run cypress using cy.realSwipe 

### ISSUE THREAD

**Issue by Strezzo06** [dmtrKovalenko/cypress-real-events#564]
As a topic, i would like to see simulating real user interactions when swipe from start point to end point, anyone have any idea to show swipe path please?

**Comment by dmtrKovalenko** [comment]
Ohh I actually think this is too much for this plugin. It only means to be used as the last hope for people who failed to use original cypress. 

Alternatively when you click the command it displays a dot of starting the touch. Just add there the length to the side and it will be a path :D
