### ISSUE TITLE
Scroll on second test after first one does not work 

### ISSUE THREAD

**Issue by MilanNicic** [dmtrKovalenko/cypress-real-events#570]
So I have 2 tests that verifies :hover with realHover(). I already had reach out to you about issue in the past and you told me to add {scrollBehaviour: false} and it indeed fixed my issue. But now what I saw that somehow when I have 2 tests that are using realHover({scrollBehaviour: false). If you run them separately, they work. But if you run all tests, one of these 2 fail, 99% of the time its 2nd test that uses realHover the one that fails, but it happens first test to fail and second test to pass rarely tho. Github repo for reproducible example here: 
https://github.com/MilanNicic/hover-reproducible-example

Best Regards

**Comment by dmtrKovalenko** [comment]
there is an answer in readme: https://github.com/dmtrKovalenko/cypress-real-events#2-when-i-am-doing-cyrealhover-hovering-state-is-not-resetting-after-my-checks
