### ISSUE TITLE
[Question] Is there any guidance for using Cypress Real Events inside a Docker container?

### ISSUE THREAD

**Issue by 1Copenut** [dmtrKovalenko/cypress-real-events#574]
## Description
I'm using CRE to more accurately create component and e2e tests that use keypress events instead of the mouse. These are a big benefit for accessibility regression.

I'm moving over to running these tests in a Docker container and getting test failures where I use CRE methods like `realPress()` and `realClick()`.

## The hypothesis
I think the issue is not with CRE, but more with exposing the Chrome Devtools Protocol to Cypress in a container. I've done a fair bit of Googling, but haven't come across anyone running into this issue or good suggestions for fixes.

## Dockerfile
The [Dockerfile is pretty basic](https://github.com/elastic/eui/blob/main/scripts/docker-ci/Dockerfile), just building a Node image with latest Chrome stable on Debian 12. Any suggestions or ideas are much appreciated.

**Comment by dmtrKovalenko** [comment]
I don’t have a lot of time to test but we do run all of our CI in docker containers anyway. You can check out our CI which is working in Docker perfectly. 

Here are docker containers handcrafted by the cypress team that include all the necessary deps and browsers: https://github.com/cypress-io/cypress-docker-images

**Comment by 1Copenut** [comment]
Thank you, I'll give these a look.

**Comment by dmtrKovalenko** [comment]
Closing for now feel free to open new issue
