### ISSUE TITLE
Discrepancy in the properties of pointerdown event triggered by realClick

### ISSUE THREAD

**Issue by alirezamirian** [dmtrKovalenko/cypress-real-events#576]
Pointerdown events triggered as a result of calling realClick, have `pressure` 0, but in a real click, `pressure` is .5 in Chrome and Firefox. That  can make code that uses [libraries which are sensitive to those properties](https://github.com/adobe/react-spectrum/blob/068ecd12e8a8c61546dfda691b04ca87cbdae687/packages/%40react-aria/utils/src/isVirtualEvent.ts#L42C17-L42C38) behave differently when testing with cypress.

### Suggested solution

Add `force: 0.5`, to the `Input.dispatchMouseEvent` cdp command params. [it's supported](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchMouseEvent) and sets `pressure` in the triggered event. I can open a PR if I get the green light.

If for some reason it's not acceptable to set force to 0.5 by default, an option would also make it possible to work around the issue.

**Comment by dmtrKovalenko** [comment]
Yes I think it’s reasonable to set the default to cypress **and provide an option**. Feel free to open a pr
