### ISSUE TITLE
realClick hangs in cypress 13

### ISSUE THREAD

**Issue by Abhi-0923** [dmtrKovalenko/cypress-real-events#580]
Hey folks,

We have been using realClick() at many a places. What we are seeing now is that cy.realClick() is hanging the cypress 13 runner.

Could you have a look at this problem?

Let me know if anymore information be needed.

Cheers,
Abhi

**Comment by dmtrKovalenko** [comment]
We are having no issues with our CI. Please create a reproduction of the problem
