### ISSUE TITLE
remote:debugger:protocol issue (firefox only)

### ISSUE THREAD

**Issue by maximegheraille** [dmtrKovalenko/cypress-real-events#588]
Hi,

I keep getting this specific error on firefox only `Error: Failed request to chrome devtools protocol. This can happen if cypress lost connection to the browser or the command itself is not valid. Original cypress error: Error: No handler registered for: 'remote:debugger:protocol'` coming from `fireCdpCommand.js`.

It fails in my custom function where I have 
`element
				.realHover()
				.then(($el) => {
					return window
						.getComputedStyle($el[0], style)
						.getPropertyValue(property);
				})
				.should('eq', match);`

Seems a bit strange it tries to connect to 'chrome' devtools no ?

It works completely fine on Chrome and electron

**Comment by dmtrKovalenko** [comment]
Please read the readme first. **cypress real events does not support Firefox**
