### ISSUE TITLE
Test after using a real-event command is not executed

### ISSUE THREAD

**Issue by pc11000** [dmtrKovalenko/cypress-real-events#597]
When I use a real event command the next test is not executed anymore. 
Why is that? Is that a known issue?

**Comment by dmtrKovalenko** [comment]
Provide a clean reproduction as separate repository with 2 tests, otherwise this issue will be ignored.

**Comment by pc11000** [comment]
I can not share it as its a company project. I saw when I execute it in Chrome it shows the native Browser Dialog if I want to reload the site. And then the next test is not executed anymore.

**Comment by dmtrKovalenko** [comment]
Be so kind and make a new **standalone** reproduction. If it’s not done I’ll close an issues
