### ISSUE TITLE
Cyrillic letters are not supported for the realType function

### ISSUE THREAD

**Issue by Halynsky** [dmtrKovalenko/cypress-real-events#614]
Cyrillic letters are not supported for the realType function

![image](https://github.com/dmtrKovalenko/cypress-real-events/assets/8502557/1b53a021-0b42-4305-bb5b-2340558abcd6)

**Comment by dmtrKovalenko** [comment]
And they are not designed to be supported. You can use text option on the real type to submit utf-8 text

**Comment by Halynsky** [comment]
@dmtrKovalenko Thx for your response. 
1 - Just interesting. Why it's designed like that?
2 - Can you please show some example of what you mean about `utf-8`? I don't see any option `utf-8` in the function itself. Do you mean some conversation before the function?

**Comment by dmtrKovalenko** [comment]
I am sorry it actually not implemented. There is a cdp option text that we can leverage for those.

PRs are welcome. For reference check how puppeteer is doing that, our type is basically a replication of puppeteer keypress. 

Need to handle and use the "text" option exclusively in realPress

**Comment by dmtrKovalenko** [comment]
I'd say that for a better design it would be easier and better to use the default cypress commands. Neither playwright nor puppeteer actually support native non english keyboards
