### ISSUE TITLE
Missing "getCypressElementCoordinates" import in latest version and exception is thrown 'not a function'

### ISSUE THREAD

**Issue by AhmedMAnwar** [dmtrKovalenko/cypress-real-events#628]
After installing the latest version 1.11.0, I got an error that 'getCypressElementCoordinates' is not resolved by the node module.

- To fix the issue: I have downgraded to version number 1.10, and all works fine with me.

- The function doesn't work was 'realHover', 'realClick', and may other functions

**Comment by dmtrKovalenko** [comment]
Need more details and a way to reproduce this error in order to help you

**Comment by AhmedMAnwar** [comment]
@dmtrKovalenko Thanks for the quick response. I just installed the latest version of the plugin, and while using the realClick()  method, I just an exception is thrown in the console logs showing that " 'getCypressElementCoordinates'" is not resolved. After more investigation, I found this method doesn't exist at all in the node module package.

**Comment by dmtrKovalenko** [comment]
If this will be a real issue nobody will be able to use this lib but taking into account amount of downloads Id guess this is your local issue. Feel free to provide more details if you still think this is a real one.

**Comment by AhmedMAnwar** [comment]
I guess I already did a cleaning for my package installation, and it didn't work at all.

**Comment by dmtrKovalenko** [comment]
closing as no more complains were made
