### ISSUE TITLE
Cypress real events are not working in Firefox

### ISSUE THREAD

**Issue by suryatejah** [dmtrKovalenko/cypress-real-events#650]
When I tried to run cypress tests against Firefox browser, could see failures because of chrome debug protocol. Do we have any plans to support [Firefox debug protocol](https://firefox-source-docs.mozilla.org/devtools/backend/protocol.html) as well or any alternatives for it?

## Error log
>  Failed request to chrome devtools protocol. This can happen if cypress lost connection to the browser or the command itself is not valid. Original cypress error: Error: No handler registered for: 'remote:debugger:protocol'

## screenshot

<img width="455" alt="image" src="https://github.com/dmtrKovalenko/cypress-real-events/assets/5953851/2469883f-006d-403a-b8fb-b7e909df2266">

**Comment by dmtrKovalenko** [comment]
Readme claims that this project does not work in firefox
