### ISSUE TITLE
`realType` not supporting `{moveToEnd}`

### ISSUE THREAD

**Issue by Wilt** [dmtrKovalenko/cypress-real-events#653]
I found that some of the commands mentioned here (like `{moveToEnd}`) aren't supported by `realType` while other commands like `{backspace}` and `{enter}` are working fine. 
Is there a reason why those other commands aren't supported and if not, would it be possible to implement the whole list mentioned here: https://docs.cypress.io/api/commands/type#Arguments?

When using `{moveToEnd}` I get the following error output:

> Unrecognized character "{moveToEnd}".

**Comment by shakcho** [comment]
I also checked `{moveToEnd}`, `{moveToStart}`, `{selectall}`, `{meta}` is not supported.
I tried to achieve the same using 

```
cy.realPress(['Control', 'a'])
cy.realType(`{end}`) 
```
to achieve` {moveToEnd}` but looks like Ctrl+a is also not working as expected. 

any idea how we can achieve the functionality of `{moveToEnd}` using realType?

**Comment by nnaydenow** [comment]
Any updates on this because I'm trying to simulate select all, cut and paste using in similar way?

```
    cy.realPress(["Meta", "a"])
    cy.realPress(["Meta", "x"])
    cy.realPress(["Meta", "v"])
```

**Comment by dmtrKovalenko** [comment]
this is a bit weird though to call Home key as move to end

**Comment by dmtrKovalenko** [comment]
I am not sure why text selection from keyboard not working but you can use 

```js
    cy.get("input[name=q]").realClick({ clickCount: 2 });
```

to simulate native selection
