### ISSUE TITLE
getting leave site pop up while using realClick();

### ISSUE THREAD

**Issue by satya081** [dmtrKovalenko/cypress-real-events#669]
When i am clicking through mouse there is no such leave site pop up i am getting  but when i am using below command i am getting this leave site pop up which is pausing the execution. Kindly help.

cy.get('#id').realClick(); 

![image](https://github.com/dmtrKovalenko/cypress-real-events/assets/32022027/14ead7eb-69d5-41c6-912d-0afeaf16db7e)

**Comment by dmtrKovalenko** [comment]
tldr 
you can close it with `cy.realType("Enter")`

https://github.com/dmtrKovalenko/cypress-real-events?tab=readme-ov-file#3-why-do-i-get-are-you-sure-popups-when-i-am-using-real-events-and-why-i-do-not-get-them-while-using-the-normal-cypress-clicks

**Comment by satya081** [comment]
@dmtrKovalenko i have added  cy.realType("Enter"); to close the alert but it is not working. also went through the given url. Those solutions are also not working for me. Kindly help me.

**Comment by dmtrKovalenko** [comment]
I'd be happy to, but I can't.

**Comment by satya081** [comment]
@dmtrKovalenko That means you are saying that this is bug of realClick() method in cypress-real-events plugin

**Comment by dmtrKovalenko** [comment]
No this means that your site is showing a popup that you need to close

**Comment by satya081** [comment]
this pop up is not showing when i am doing it manually. only when i am using realClick() method.

**Comment by satya081** [comment]
there is bug https://github.com/cypress-io/cypress/issues/28553 which is in open state
