### ISSUE TITLE
Question: is this plugin possible in Firefox using their CDP?

### ISSUE THREAD

**Issue by steveworkman** [dmtrKovalenko/cypress-real-events#676]
Hello - firstly, I'm well aware that this project only works in Chromium and it says so in the readme. My understanding is that this is because the project uses the [Chrome Devtools Protocol](https://chromedevtools.github.io/devtools-protocol/) to fire the events in a trusted way.

Firefox has some support for CDP though it is incomplete, or ["half-baked" as claimed over in SeleniumHQ](https://github.com/SeleniumHQ/selenium/issues/11736) with Firefox's focus being on [WebDriver BiDi](https://w3c.github.io/webdriver-bidi/).

Two questions:
- Is this plugin even possible with the current CDP implementation in Firefox
- Would the plugin be able to use BiDi instead?

**Comment by dmtrKovalenko** [comment]
No and no 
We are reusing the same connection that cypress maintains and it is doing this only for a chrome browser
