### ISSUE TITLE
Flakiness with realPress

### ISSUE THREAD

**Issue by philipbushnell-valtech** [dmtrKovalenko/cypress-real-events#678]
It seems that `realPress` doesn't always trigger the focused element. I have the following code:

```ts
cy.findByRole('button', { name: 'Open' }).focus();

// passes always
cy.findByRole('button', { name: 'Open' }).should('be.focused'); 

cy.realPress('Enter');

// fails sometimes as the menu is not actually opened by the press
cy.findByRole('heading', { name: 'Heading Text' }).should('be.visible'); 
```

I'm on the latest version (`1.12.0`) and this is quite frustrating when it fails. I'm explicitly checking keyboard navigation so I cannot replace it with click.

**Comment by dmtrKovalenko** [comment]
I need a more descriptive standalone example. Please make a repo that clearly displays the flakieness

**Comment by philipbushnell-valtech** [comment]
That's the issue, it's flaky. You could run it 10 times and it passes fine but then on the 11th it'll fail so there's no way to clearly display it for you. There's nothing special or exciting about the code; it's just a button with an `onClick` handler that causes a rerender to now make something visible.

**Comment by dmtrKovalenko** [comment]
I won't be able to look into the issue until there would be a clear concise reproduction of flakieness.
