### ISSUE TITLE
.realPress('{enter}') does not trigger buttons, .realPress('Space') does

### ISSUE THREAD

**Issue by noahgelman** [dmtrKovalenko/cypress-real-events#8]
The {enter} realPress event does not trigger events on things like buttons and links. Space will trigger them however, which is a placeholder for now

**Comment by tomkaX** [comment]
Will working on this task

**Comment by noahgelman** [comment]
@tomkaX  @dmtrKovalenko 
Any update on this?

**Comment by noahgelman** [comment]
@dmtrKovalenko I'm not sure what you mean. Buttons can be triggered by pressing "Enter", but not with cypress-real-events

**Comment by NVD-JIT** [comment]
@dmtrKovalenko There is no way to use real press to press "Enter" right now, I think you should be looking into this.
