### ISSUE TITLE
`.realHover()` effect is not captured in `cy.screenshot()`

### ISSUE THREAD

**Issue by nemanjaglumac** [dmtrKovalenko/cypress-real-events#80]
Hi @dmtrKovalenko ,
first of all thank you for this amazing library!

I was trying to use `realHover()` in combination with Cypress `cy.screenshot()`. While I can easily see the effect of real hover in test GUI, the moment the screenshot is taken, that effect is gone.

On top of that, the hover effect doesn't persist even in Cypress' own DOM snapshots (in the GUI runner). Please see the GIF below:
https://share.getcloudapp.com/Z4uoRyem

Is there any way this effect can be persisted (forced?) or are there technical limitations obstructing that?
Thank you in advance and please let me know if I can provide more details.

**Comment by dmtrKovalenko** [comment]
Yeah this is likely impossible :)

Cypress is doing some work in preparation between screenshot that will break hover

**Comment by nemanjaglumac** [comment]
That's a pity 😞
Thank you for the prompt answer, though! Appreciate it.

**Comment by deepanshubatra** [comment]
@nemanjaglumac Hey there !
Were you able to capture screenshots in hovered state through any other means ?

I am facing the same issue ,I thought you might be able to help.

**Comment by AvtandilG** [comment]
@deepanshubatra @nemanjaglumac 

Were you able to find any solution?

**Comment by nemanjaglumac** [comment]
@deepanshubatra @AvtandilG - unfortunately, still no luck :/

Sorry for the late reply, btw.

**Comment by kiocosta** [comment]
Has anyone been able to find a solution or workaround for this?

**Comment by warri93** [comment]
Is this one resolved? If so, how? Cause I am still having the same issue :/

**Comment by kiocosta** [comment]
> Is this one resolved? If so, how? Cause I am still having the same issue :/ I do not want to set the css manually

I believe this won't be solved in a clean way for a while... as it was already stated:

> Yeah this is likely impossible :)
> Cypress is doing some work in preparation between screenshot that will break hover

In order to fix this, I believe it's necessary to change the way Cypress takes screenshots so it doesn't break the hover effect. You could do a fork of Cypress, do that yourself and then open a Pull Request for it, but I guess it would consume more time you'd like to spend.
