### ISSUE TITLE
Is this possible to hover on x y Point by using realHover

### ISSUE THREAD

**Issue by sunilvishkarma** [dmtrKovalenko/cypress-real-events#89]
I want to perform hover on XY point on the element.

Can we hover on XY Point passing by using realHover?

**Comment by dmtrKovalenko** [comment]
Yes the type of `position` property is 
```ts
export type Position =
  | "topLeft"
  | "top"
  | "topRight"
  | "left"
  | "center"
  | "right"
  | "bottomLeft"
  | "bottom"
  | "bottomRight"
  | { x: number; y: number };
 ```
 
 So if you will pass `cy.realHover({ position: { x: 10, y: 10 }})` it will hover at x:10;y:10 coordinate relative to the element
