### ISSUE TITLE
realTouch() Absolute Coordinates does not respect Viewport size

### ISSUE THREAD

**Issue by OlivierHess** [dmtrKovalenko/cypress-real-events#94]
Hi,

I have the viewport size set in a Cypress test to `cy.viewport(1280, 720);`, however the realTouch() does not always have the correct absolute coordinates when the browser is resized - I believe this is because the coordinates are calculated based on the `iframe` rather than the Html or Body element of the page. 

For example, if I run my test on a full page width, the calculated absolute coordinates are x: 1254 and y: 177. If I resize my window, the coordinates change to x:1221 and y:177, even though my viewport is locked to 1280x720px.

![image](https://user-images.githubusercontent.com/12977892/120690778-8d08b600-c49d-11eb-87f2-fd7f67e24dc9.png)

![image](https://user-images.githubusercontent.com/12977892/120691011-d527d880-c49d-11eb-89cf-c1a0b2243b1b.png)

**Comment by dmtrKovalenko** [comment]
It calculates a real coordinate. On the main tab (not your iframe) so it can be any number bigger than viewport. The main question – can you make a reproduction so we can understand exactly why it can not detect particular element

**Comment by OlivierHess** [comment]
Sure, it should be pretty easy to replicate. Let's say you have a Cypress test with a fixed viewport set at 1280x720px, you add a test to do a touchstart `realTouch` with the coordinates `{ x: 650, y: 130}`. The test passes until you resize your browser window, then it starts to fail. As an example, if my browser window is 2000px wide the test passes, if I resize to 1500px the test fails. My target is at the same location with the fixed viewport.

**Comment by OlivierHess** [comment]
I forgot to mention a **very** important detail, I'm running the test in the Cypress browser (via `cypress open` command). This is where I can see the behaviour I explained above.

**Comment by dmtrKovalenko** [comment]
This is how it works by the way. Chrome CDP doesn't know anything about your viewport. We need to calculate element coordinate on the tab with a correct shift to the iframe `scale()` and so on.

https://github.com/dmtrKovalenko/cypress-real-events/blob/4fd016db8f855dac3a0651d55257573fa8bd5a5f/src/getCypressElementCoordinates.ts#L25

So your custom coorniate should relate also the whole tab root
