### ISSUE TITLE
RealPress not firing click events on button elements

### ISSUE THREAD

**Issue by marcysutton** [dmtrKovalenko/cypress-real-events#95]
Hi there, thanks for the great project! I was excited to find it since I ran into issues with [Cypress not firing native events (and it not being on their roadmap)](https://github.com/cypress-io/cypress/issues/311#issuecomment-787508664). This tool is promising for keyboard accessibility testing! But as far as I can tell, the Enter key still doesn't work the same way browsers do as of version 1.5.1. Specifically, hitting the Enter key on a Button element should fire a native click event and handler callback function. In Cypress-Real-Events, the event is getting lost somewhere in the stack. The tests added in https://github.com/dmtrKovalenko/cypress-real-events/pull/69 work for putting text into an Input element, but not firing a callback function on an interactive element's click handler.

I looked into the code a bit and saw RealPress is successfully catching the user event and firing off `Input.dispatchKeyEvent` to the DevTools protocol. But on multiple repos where I tested it, the click handler attached to a button won't fire on the Enter key. This is important for writing keyboard accessibility tests that mimic user behavior, so we can differentiate between things like `<div tabindex="0" onclick="handleClick()">` and `<button onclick="handleClick()>`, where the div will fail to function without a key handler but the button will click on Enter.

## How to test

I've added a failing test for this behavior in my fork, I'd be happy to submit a PR for it: https://github.com/marcysutton/cypress-real-events/commit/70f8b735e29b805007ab0ac40b7ed3cbadfaf201

Here's a live test page I made where you can compare the user experience with your keyboard to what Cypress-Real-Events is doing: https://marcy.codes/testing/cypress-real-events/

## Screenshots

In my test page, when a user presses the Enter key on a button element it appends text to a DIV:
<img width="600" alt="Cypress Test page showing a focused button and event details appended to the screen" src="https://user-images.githubusercontent.com/1045233/120856804-33ec6100-c535-11eb-8750-0d805e86d5fa.png">

With Cypress-Real-Events, the text is never appended to the DIV when `.realPress('Enter')` is fired on the button:
<img width="1159" alt="Cypress App opened to a RealPress test showing the button failing to operate" src="https://user-images.githubusercontent.com/1045233/120856971-73b34880-c535-11eb-8aea-43dd56ae59a6.png">

---

If you have any tips (and if I'm not missing something obvious), I could potentially work on a PR. I'd love to get this working. Thanks!

**Comment by dmtrKovalenko** [comment]
Thanks for this qualified reproduction, this helps a lot! 🙏
